### ISSUE TITLE
invoke Insanity

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/quest-compiler#4]
Lots of Quest code passes an object (same as a Quest object dictionary) made up of keys and values as a single parameter to ```invoke()```.

I need to find code to cover any possible parameters being passed via object.

**Comment by tass23** [comment]
Can you show me an example?
I don't understand why it wouldn't grab all the parameters in the first place...?
Is it only grabbing Quest parameters, and not user parameters?
I would think a separate function to gather the user params, then combine that with the object dictionary with keys and values, then the whole thing gets sent to invoke(), should do it.

**Comment by KVonGit** [comment]
Using the text processor is the main thing that calls ```invoke```, as far as I can tell.

```invoke``` calls a script, and you can send a Quest dictionary as a parameter. The keys of the dictionary will be used as parameter names in the script Quest calls, and the values of those keys will be the values of the parameters.


Quest does this:

```xml
    params = NewDictionary()
    dictionary add (params, "section", section)
    dictionary add (params, "data", data)
    foreach (command, game.textprocessorcommands) {
      if (StartsWith(section, command)) {
        invoke (ScriptDictionaryItem(game.textprocessorcommands, command), params)

// This code goes on and on...

```

---
Alright, so, ```game.textprocessorcommands``` is a script dictionary attribute. It takes the parameters ```section``` and ```data```.

You know what... I can't really explain the text processor functions fully.

I avoid the text processor commands, honestly.

Here is the code for ```game.textprocessorcommands``` in Quest:

<details><summary><b>game.textprocessorcommands</b></summary>

```xml
    <textprocessorcommands type="scriptdictionary">
      <item key="if ">
        game.textprocessorcommandresult = ProcessTextCommand_If (section, data)
      </item>
      <item key="either ">
        game.textprocessorcommandresult = ProcessTextCommand_Either (section, data)
      </item>
      <item key="here ">
        game.textprocessorcommandresult = ProcessTextCommand_Here (section, data)
      </item>
      <item key="nothere ">
        game.textprocessorcommandresult = ProcessTextCommand_Here (section, data)
      </item>
      <item key="popup:">
        game.textprocessorcommandresult = ProcessTextCommand_Popup (section, data)
      </item>
      <item key="i:">
        game.textprocessorcommandresult = ProcessTextCommand_Format (section, data)
      </item>
      <item key="b:">
        game.textprocessorcommandresult = ProcessTextCommand_Format (section, data)
      </item>
      <item key="s:">
        game.textprocessorcommandresult = ProcessTextCommand_Format (section, data)
      </item>
      <item key="u:">
        game.textprocessorcommandresult = ProcessTextCommand_Format (section, data)
      </item>
      <item key="colour:">
        game.textprocessorcommandresult = ProcessTextCommand_Colour (section, data)
      </item>
      <item key="color:">
        game.textprocessorcommandresult = ProcessTextCommand_Colour (section, data)
      </item>
      <item key="back:">
        game.textprocessorcommandresult = ProcessTextCommand_Colour (section, data)
      </item>
      <item key="object:">
        game.textprocessorcommandresult = ProcessTextCommand_Object (section, data)
      </item>
      <item key="command:">
        game.textprocessorcommandresult = ProcessTextCommand_Command (section, data)
      </item>
      <item key="page:">
        game.textprocessorcommandresult = ProcessTextCommand_Command (section, data)
      </item>
      <item key="exit:">
        game.textprocessorcommandresult = ProcessTextCommand_Exit (section, data)
      </item>
      <item key="once:">
        game.textprocessorcommandresult = ProcessTextCommand_Once (section, data)
      </item>
      <item key="notfirst:">
        game.textprocessorcommandresult = ProcessTextCommand_NotFirst (section, data)
      </item>
      <item key="random:">
        game.textprocessorcommandresult = ProcessTextCommand_Random (section, data)
      </item>
      <item key="rndalt:">
        game.textprocessorcommandresult = ProcessTextCommand_RandomAlias (section, data)
      </item>
      <item key="img:">
        game.textprocessorcommandresult = ProcessTextCommand_Img (section, data)
      </item>
      <item key="counter:">
        game.textprocessorcommandresult = ProcessTextCommand_Counter (section, data)
      </item>
      <item key="select:">
        game.textprocessorcommandresult = ProcessTextCommand_Select (section, data)
      </item>
      <item key="eval:">
        game.textprocessorcommandresult = ProcessTextCommand_Eval (section, data)
      </item>
      <item key="=">
        game.textprocessorcommandresult = ProcessTextCommand_Eval (section, data)
      </item>
    </textprocessorcommands>

```

</details>

---
The problem when converting that to JS is that the property (known as an attribute in Quest) is a function (called a script in this instance in Quest) that does not declare its parameters.

Note that the text processor is not the only thing that calls ``invoke```, not by a long shot, but it is used like almost every turn in your game. Lots of other people use it all the time, too. I'm not bashing or anything. Anyway...

This is the way the text processor stuff works in the recent version of Quest.

Before that update, the main text processor code was this:

```xml
  <function name="ProcessText" parameters="text" type="string">
    data = NewDictionary()
    dictionary add (data, "fulltext", text)
    text = ProcessTextSection(text, data)
    return (Replace(Replace(text, "@@@open@@@", "{"), "@@@close@@@", "}"))
  </function>
```

---
It didn't use a script attribute on the ```game``` object, and it didn't use ```invoke```.

---
Now, I told you all that because that was the main reason the converter wouldn't work with games made by the recent version of Quest. I fixed that recently, though.

In Quest, ```invoke``` is a hard-coded script. So it's doing stuff deep in the code, and you can't see what it's doing and you can't fool with it at all from inside Quest. You can only call it with parameters.

So, Alex Warren made JS functions for each of his Quest scripts like ```invoke``` when he made this converter.

Back then, it was like Quest 5.2 or something, and this text processor stuff wasn't a thing that used ```invoke```. Alex generally knew when ```invoke``` was used back then, so his JS version of the function covered everything Quest used ```invoke``` for by default.

```js
function invoke(script, parameters) {
    if (parameters) {
        script.apply(null, [parameters["result"]]);
    } else {
        script();
    }
}
```

---
That was the whole function, and it mostly handled things properly, unless someone was using ```invoke``` differently in scripts they'd added to their game. In those cases, Alex said, "if you can add scripts to your game, you can fix the code when you convert your game, too."

Anyway, here is the current version of that in the recent converter's game.js:

```js
function invoke(script, parameters) { 
/* Fix for Quest 5.8.0 Build 5.8.7753.35198 */
    /*var clog = console.log;
	clog("invoke script:");
	clog(script.toString());
	if (script.toString() === 'function() { set(_obj311, "textprocessorcommandresult", ProcessTextCommand_Popup (section, data)); }'){
		clog("IT'S POPUP!");
	}*/
	if (parameters) {
		/*clog("invoke parameters:");
		clog(parameters);
		clog("Doing forEach..");
		function findParams(key){
			clog("key:");
			clog(key);
			clog("parameters[key]");
			clog(parameters[key]);
		}
		Object.keys(parameters).forEach(findParams);*/
        if (parameters["this"]) {
            script.apply(parameters["this"], [parameters]);
        } else if (parameters["section"]) {
			var sectionVar = parameters["section"];
			var dataVar = parameters["data"];
            script.apply(section = sectionVar, data=dataVar);
        } else if (parameters["result"]) {
            script.apply(null, [parameters["result"]], parameters);
        } else {
            console.log("invoke is blindly sending 'parameters':");
            console.log(parameters);
            script.apply(null, parameters);
        }
    } else {
        script();
    }
}
```

---
First off, damn, I left a lot of debugging messages to the console log in there, hehehe.

Anyway, can you look at the old versus the new and kind of see what is maybe kind of possibly probably unknowingly happening?

The real problem is you never know what might be in the Object Dictionary being sent as parameters. Each of its attributes is a key, and the value to which each key points could be a string or an object or a list (aka an array in JS) or a script. Any attribute could be named anything, too, and there's no limit to the number of attributes there might be.

TO COMPLICATE THAT, there's no telling what script (or function) ```invoke``` might be calling. If whatever it is calling has declared parameters, everything *usually* works, but if it is a script attribute (like ```game.textprocessorcommands```), then it will have no parameters, and you can't assign any in Quest.

So, the best thing about Quest is being able to customize everything, and that includes using ```invoke``` however you please to your heart's content if you wish to do so. So...

The ```invoke``` function in the converter needs to do stuff I simply don't know how to handle. Sometimes, this line needs to have the parameters like this: ```script.apply(parameters["this"], [parameters]);```

Other times it needs to have the parameters like this: ```script.apply(null, [parameters["result"]], parameters);```

And I don't know how to tell JS to check which one it needs to use. The only fix I've found is to add code to handle things specifically, and that just isn't the right way to handle it at all.

Someone might be doing crazy stuff like this: https://textadventures.co.uk/forum/quest/topic/rdsytxt6c0yifvmddy7cba/running-a-command-verb-via-a-script#19afb6d4-bbae-46a5-8f48-aae99a40ec58

---
To top all of this off, anything changed in the JS version of ```invoke``` in ```game.js``` needs to work the same way (or as close as possible to the way) that Quest works, and I can't expect people to add code to their Quest games in order to work in the converter. Else, the main purpose of the converter, as far as most users are concerned, would be negated.

This is why I abandoned the converter. It is always going to end up having issues, and even when I fix most of them, something new pops up in a Quest game that opens two or three unknown cans of worms in the converter.

Also, everything is so intricate, every time I fix the code to work with one thing, that breaks 100 other things.

For instance, I can get the panes to work 99% correctly, but that makes it so clicking the little button to show the menu to restart the game opens a new tab with the game in it showing the GAME OVER screen. You flip back to the original tab, and everything is right there and you can click restart.

I fixed it so clicking the little button didn't send its ```onclick``` crap through to propagate, but that made it so that clicking on items in the pane did nothing. At this point, I went outside and furiously spat towards the woods between my neighborhood and a Google building. Even though Google had nothing to do with this specific issue, everything is using Chromium so I feel justified.

Wait... What was the question again?

**Comment by KVonGit** [comment]
Before I go to bed, I'll leave this right here:

```js
	if (parameters) {
		clog("invoke parameters:");
		clog(parameters);
		clog("Doing forEach..");
		function findParams(key){
			clog("key:");
			clog(key);
			clog("parameters[key]");
			clog(parameters[key]);
		}
		Object.keys(parameters).forEach(findParams);
```

---
I could make the ```findParams()``` function return each key and value, but I still won't know when to set the first parameter to ```null``` or the second parameter to an array or an object or an array with a nested object or... yeah.

Plus, there are endless possibilities of what the code might be sending and calling from a Quest game. It might even me a custom function. There's no way to cover it to my knowledge.

**Comment by KVonGit** [comment]
This is the point where last time I was working on this, I decided it would be easier to write my own parser games in JS from the ground up, and I did. Well, I mean... It's functional. Nothing noteworthy.

Point is, this issue combined with the jQuery accordion issue and the colors and HTML image elements behaving unexpectedly is overwhelming. I've attacked issue on its own, and each each leads to numerous other issues. I'm assuming this is why the original creator also abandoned this before ever releasing it and tried to create his own parser games in JS from the ground up, and he did. Well, I mean, it wasn't really game code written in JS. Whatever language it was, that's what QuestKit was.

What was I talking about? Oh yeah... I know not about the code used to render maps or work with coordinates, and I can barely make things work in CSS by poking around from the developer tools console. Those things are really the main issues now.

There's really nothing else in Quest that uses ```invoke``` by default that wouldn't have thrown an error by now, I don't think. So, as long as you don't directly add ```invoke``` to anything in your game, the way it's coded now, ```invoke()``` should be a non-issue (I think).

It just makes me frustrated that I can't fully figure out how to code it to handle anything ever possibly thrown at it, but I guess sometimes that's just impossible with some functions.


---
Sorry for ranting and rambling. I'm not saying I won't try to work on any issues anymore. I just don't know how to approach the map or the CSS stuff (which is what is doing odd things with the colors and the game panes), and I've reached the point where I'm good with just disabling stuff like that in the converter by default. Authors who are messing with all that will know how (or be able to quickly figure out how) to edit the files in the converted game's folder to their liking.

Dang... Now I sound like Alex, and I once thought he seemed a bit short when discussing such things. I'm not trying to be rude or anything; I promise. I'm fine with giving up on a couple of cosmetic things, at least for a while. (I just hate letting the code beat me, haha.)

**Comment by tass23** [comment]
Can you show me, like with a screenshot what you're seeing? CSS can use wildcards to target text inside the tags, so that might be one route.Doesn't the map have pre-defined values? Like a map doesn't have Ask/Tell, doesn't have Inventory, that sort of thing, so some data types are not used. I don't know what the map is looking for, or what Quest is generating, but we only need 2 values to make a position: X and Y, and it doesn't even have to be that complex. Forward, Back, In, Out, Up, Down, Left, Right, are the only available directions. Non-Directional exits "wipe" the map, so when you use one of those exits the map starts over with a blank space.Another way to go about it would be to manually align the exits in Quest, then the Compiler just uses those values. Like a Drag/Drop pane with 9 tiles, 3x3, center is the current room.Anyway, if the map is limited to the space on the screen: a 3x3 layout, once you go off that space, the space resets with a clean screen, player in the center square. You're never going beyond that 3x3 layout.I can push some things to ChatGPT and see if we can get pointed in the right direction. I was caught in a loop of game not being identified and loadGame not being called because of game definition under init function. I tried moving function loadGame above function init, but that didn't matter. There was only one game.js in the game folder, and the Math functions were repeated twice in the compiled game.js. There was only one set inside the Compiler game.js, so why is it adding a second set? There's not a second game.js file.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: "K.V." ***@***.***> Date: 8/13/24  12:45 AM  (GMT-05:00) To: KVonGit/quest-compiler ***@***.***> Cc: Raist ***@***.***>, Comment ***@***.***> Subject: Re: [KVonGit/quest-compiler] invoke Insanity (Issue #4) 
This is the point where last time I was working on this, I decided it would be easier to write my own parser games in JS from the ground up, and I did. Well, I mean... It's functional. Nothing noteworthy.
Point is, this issue combined with the jQuery accordion issue and the colors and HTML image elements behaving unexpectedly is overwhelming. I've attacked issue on its own, and each each leads to numerous other issues. I'm assuming this is why the original creator also abandoned this before ever releasing it and tried to create his own parser games in JS from the ground up, and he did. Well, I mean, it wasn't really game code written in JS. Whatever language it was, that's what QuestKit was.
What was I talking about? Oh yeah... I know not about the code used to render maps or work with coordinates, and I can barely make things work in CSS by poking around from the developer tools console. Those things are really the main issues now.
There's really nothing else in Quest that uses invoke by default that wouldn't have thrown an error by now, I don't think. So, as long as you don't directly add invoke to anything in your game, the way it's coded now, invoke() should be a non-issue (I think).
It just makes me frustrated that I can't fully figure out how to code it to handle anything ever possibly thrown at it, but I guess sometimes that's just impossible with some functions.

Sorry for ranting and rambling. I'm not saying I won't try to work on any issues anymore. I just don't know how to approach the map or the CSS stuff (which is what is doing odd things with the colors and the game panes), and I've reached the point where I'm good with just disabling stuff like that in the converter by default. Authors who are messing with all that will know how (or be able to quickly figure out how) to edit the files in the converted game's folder to their liking.
Dang... Now I sound like Alex, and I once thought he seemed a bit short when discussing such things. I'm not trying to be rude or anything; I promise. I'm fine with giving up on a couple of cosmetic things, at least for a while. (I just hate letting the code beat me, haha.)

**Comment by KVonGit** [comment]
Just uploaded updated game.js and a new release that fixes lots of stuff, probably breaks some stuff too, but I didn't see ```invoke()``` breaking anything after playing for a couple of minutes.

Closing this one.
